name: img_clf
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.6
  - pip
  - git
  - jupyterlab=3
  - pandas
  - matplotlib
  - seaborn
  - opencv
  - tqdm
  - pip:
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - torch==1.9.0+cu102
    - torchvision==0.10.0+cu102
    - pytorch-lightning==1.3.6
    - albumentations==1.0.3
    - sklearn