seed: 42
input:
  image_dir: path_to_images
  labels_train_csv: data\labels_train.csv
  labels_test_csv: data\labels_test.csv
test:
  weight_path: path_to_weights
  result_folder: performance_evaluation
  file_name: results_version1.csv
model:
  class_name: torchvision.models.resnet50
  params:
    pretrained: True
    finetune: True
    freeze: False
    classes: 1
loss:
  class_name: torch.nn.BCEWithLogitsLoss
optimizer:
  class_name: torch.optim.Adam
  params:
    lr: 0.0001
scheduler:
  class_name: torch.optim.lr_scheduler.CosineAnnealingLR
  params:
    T_max: 30
data:
  k_fold: 3
  split: 0
  img_size: 256
  depth: 3
  mean: [0.485, 0.456, 0.406]
  std:  [0.229, 0.224, 0.225]
  train_loader:
    batch_size: 4
    num_workers: 8
    pin_memory: True
    shuffle: False
  val_loader:
    batch_size: 4
    num_workers: 8
    pin_memory: True
    shuffle: False
  test_loader:
    batch_size: 4
    num_workers: 1
    pin_memory: True
    shuffle: False
trainer:
  max_epochs: 50
  precision: 32
  gpus: [0]
  deterministic: True
  benchmark: True
  auto_scale_batch_size: False
  auto_lr_find: False
  resume_from_checkpoint: null
logger:
  project: "runs"
  log_model: False
  offline: False
callbacks:
  checkpoint:
    monitor: 'val_loss'
    mode: 'min'
    save_top_k: 1
    filename: 'aircrafts_classifier-{epoch:02d}-{val_loss:.2f}'
